CREATE TABLE preference_companionship (
  user_id VARCHAR(255) PRIMARY KEY COMMENT 'Primary identifier token, hexadecimal characters',
  indiapp_id VARCHAR(255) COMMENT 'Associated IndiApp ID, hexadecimal characters',
  city VARCHAR(255) COMMENT 'User city',
  coordinates POINT COMMENT 'User current coordinates',
  on_site BOOLEAN COMMENT 'Indicates whether on-site service is available',
  max_distance FLOAT COMMENT 'Maximum service distance in kilometers',
  local_type ENUM('on-site', 'hang_out', 'hotel', 'residential_hotel', 'appartement') COMMENT 'Type of location where services are provided, if no location is set by the provider, matching cannot occur',
  rdv TIME COMMENT 'Available service time range',
  services JSON COMMENT 'List of required services',
  service_time TIME COMMENT 'Required service duration',
  price_min FLOAT COMMENT 'Minimum price for the required services',
  price_max FLOAT COMMENT 'Maximum price for the required services',
  currency ENUM('USD', 'EUR', 'JPY', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'HKD', 'NZD', 'KRW', 'SGD', 'SEK', 'NOK', 'MXN', 'INR', 'RUB', 'ZAR', 'BRL', 'TRY', 'TWD', 'DKK', 'PLN', 'THB', 'IDR', 'HUF', 'CZK', 'ILS', 'MYR', 'PHP', 'PKR', 'CLP', 'AED', 'SAR', 'COP', 'EGP', 'VND', 'BDT', 'KWD', 'QAR', 'UAH', 'PEN', 'MAD', 'NGN', 'KZT', 'ARS', 'DZD', 'LKR', 'OMR', 'BHD') COMMENT 'Default currency',
  trust_score_min FLOAT COMMENT 'Minimum trust score required',
  gender SET('male', 'female', 'other') COMMENT 'Target gender list',
  age_min FLOAT COMMENT 'Minimum target age',
  age_max FLOAT COMMENT 'Maximum target age',
  nationality JSON COMMENT 'List of target nationalities',
  languages JSON COMMENT 'Languages and proficiency levels in JSON format, e.g., [{"language": "English", "level": "Fluent"}, {"language": "Spanish", "level": "Beginner"}]',
  ethnicity SET('asian', 'arab', 'black', "white", 'south_asian', 'native_american', 'pacific_islander', 'hispanic', 'other')  COMMENT 'Ethnic information, stored as a set',
  education SET('none', 'primary', 'secondary', 'bachelor', 'master', 'doctorate') COMMENT 'Education level, refer to the personal table for values',
  profession SET('healthcare', 'education', 'engineering', 'business', 'arts', 'legal', 'marketing', 'it', 'public_service', 'sales', 'hospitality', 'fashion', 'transportation', 'customer_service', 'finance', 'construction', 'manufacturing', 'KOL_media', 'research', 'office_work', 'operations', 'logistics', 'public_relations', 'consulting', 'other') COMMENT 'Profession, refer to the personal table for values'
  NSFW_interest JSON COMMENT 'NSFW interests stored as an array'
);
