Table user_accounts {
  user_id varchar [primary key, note: '主识别token，16进制字符']
  user_state enum() [note: '账户的状态']
  user_login_method varchar[] [note: '账户已经验证的登录方法，第一个就是默认登录方法']
  username varchar [unique, note: '用户名，唯一标识']
  profile_picture varchar [note: '用户头像的URL']
  bio varchar [note: '用户个人简介']
  created_at datetime [note: '用户账户创建时间']
  created_method enum('claim_invited', 'claim_provider_order', 'claim_provider_kol', 'claim_user_receive_money', 'claim_user_check_trust', 
'register_invited', 'register_unknown_user', 'register_check_trust', 'register_indiapp_user', 'register_indiapp_provider'
) [note: '用户账户创建方法']
  claimed_at datetime [note: '用户本人claim账户的时间']
  claimed_method enum('google', 'facebook', 'instagram', 'twitter', 'tiktok', 'apple_id', 'whatsapp', 'phone_number', 'email', 'telegram'
) [note: '用户本人claim账户的方法']
  updated_at datetime [note: '用户最后更新时间']
  updated_method enum('by_itv3','by_indiapp') [note: '用户最后更新方法']
}

Table login_methods {
  user_id varchar [note: '关联用户ID']
  google_id varchar [note: 'Google 用户ID Token']
  google_email varchar [note: 'Google 邮箱']
  facebook_id varchar [note: 'Facebook 用户ID']
  facebook_email varchar [note: 'Facebook 邮箱']
  instagram_id varchar [note: 'Instagram 用户ID']
  instagram_username varchar [note: 'Instagram 用户名']
  twitter_id varchar [note: 'Twitter 用户ID']
  twitter_username varchar [note: 'Twitter 用户名']
  apple_id varchar [note: 'Apple 用户ID']
  whatsapp_phone_number varchar [note: 'WhatsApp 电话号码']
  phone_verified boolean [note: '电话号码是否经过验证']
  region_number varchar [note: '电话号码区号']
  phone_number varchar [note: '电话号码']
  email_verified boolean [note: '邮箱是否经过验证']
  email_address varchar [note: '邮箱地址']
  telegram_handle varchar [note: 'Telegram 用户名']
  telegram_phone_number varchar [note: 'Telegram 登录电话']
}

Table subscriptions {
  id varchar [note: '发起订阅的人id']
  subscriber_id varchar [note: '发起订阅的人id']
  subscribed_id varchar [note: '被订阅的人id']
  method varchar [note: '用于已经在哪些平台订阅了这个人["instagram"，“facebook”]']
  created_at datetime [note: '什么时候创建的,可以用来排序']
}


Table referral_infos {
    id varchar [note: '关联用户ID']
    referrer_id varchar [note: '一级推荐者的名字']
    referee_id varchar [note: '一级被推荐者的用户ID，十六进制字符串']  
    method varchar [note: '一级推荐者使用什么方法推荐']
    created_at datetime [note: '什么时候创建的,可以用来排序']
}

Table kyc {
  user_id varchar [note: '关联用户ID']
  id varchar [note: 'KYC ID']
}

Table pot {
  user_id varchar [note: '关联用户ID']
  id varchar [note: 'POT ID']
}

Table wallet {
  user_id varchar [note: '关联用户ID']
  id varchar [note: '钱包账户']
}

Table offers {
  user_id varchar [note: '关联用户ID']
  offer_id varchar[] [note: '提供服务']
}

Table orders {
  user_id varchar [note: '关联用户ID']
  order_id varchar[] [note: '订单']
}

Table transactions {
  user_id varchar [note: '关联用户ID']
  tx_id varchar[] [note: '交易记录']
}

Table reviews {
  user_id varchar [note: '关联用户ID']
  review_id varchar[] [note: '评论记录']
}

Table settings {
  user_id varchar [note: '关联用户ID']
}

Table settings_indiapp {
  user_id varchar [note: '关联用户ID']
  indiapp_id varchar [note: '关联用户ID']
  setting json [note: '对应类型的喜好']
}

Table preferences {
  user_id varchar [note: '关联用户ID']
  offer_type varchar [note: '对应offer类型']
  preferences json [note: '对应类型的喜好']
}

Table personal {
  user_id varchar [note: '关联用户ID']
  gender varchar [note: '性别']
  birth_day date [note: '出生日期']
  nationality varchar[] [note: '国籍，存储为 数组']
  ethnicity varchar[] [note: '用户的种族信息，存储 数组']
  profession varchar [note: '职业']
  education varchar [note: '教育程度']
  
  // Languages
  languages json [note: '语言与等级的 JSON 数组，示例: [{"language": "English", "level": "Fluent"}, {"language": "Spanish", "level": "Beginner"}]']

  // Types
  style varchar[] [note: '用户自己的性格类型']
  type varchar[] [note: '用户喜欢的性格类型']
  sexual_orientation enum [note: '性取向']
  
  // Interests
  interests varchar[] [note: '兴趣数组，逗号分隔']
  NSFW_itrest varchar[] [note: 'NSFW兴趣数组，逗号分隔']

  // Physical attributes
  hair_color enum [note: '头发颜色']
  hair_length enum [note: '头发长度']
  eye_color enum [note: '眼睛颜色']
  skin_color enum [note: '肤色']
  height float [note: '身高']
  weight float [note: '体重']
  bust float [note: '胸围']
  waist float [note: '腰围']
  hips float [note: '臀围']
  body_shape enum [note: '体型']
  bra_size enum [note: '胸罩尺寸']
  plastic_surgery enum [note: '整容状况']
  tattoos enum [note: '纹身状况']
  piercings enum [note: '穿孔状况']  
}


